spring.application.name=EventRegistration_Backend
spring.datasource.url=jdbc:sqlite:src/main/resources/test.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.jpa.hibernate.ddl = create
spring.jpa.hibernate.ddl-auto=update
jwt.secret = 65626E01CCBEE7690F645A3823F3DB2E488A77BE8E29E048CE030C437051FCD6A28FCC03CEF1A9A09A2B693BF50D6DBC59E59084C4F343C7EFF2536BEC27230B